webinar/example/app/urls.py
from django.urls import path
from .views import index, StartView, ProductListView, ProductCreateView

app_name = 'app'
urlpatterns = [
    path('', index, name='index'),
    path('base/', StartView.as_view(), name='start'),
    path('product/', ProductListView.as_view(), name='products'),
    path('product/create/', ProductCreateView.as_view(), name='create'),
]

webinar/example/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

webinar/example/app/models.py
from django.db import models

# Create your models here.
class Product(models.Model):
    PRODUCT_CHOICES = (
        ('FRUIT', 'fruit'),
        ('VEGETABLE', 'vegetable'),
    )
    name = models.CharField(max_length=32)
    type = models.CharField(max_length=12, choices=PRODUCT_CHOICES, default='FRUIT')
    price = models.FloatField(default=100.0)
    description = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.name} : {self.price}'

webinar/example/app/forms.py
from .models import Product
from django.forms import ModelForm

class ProductForm(ModelForm):

    class Meta:
        model = Product
        fields = '__all__'

webinar/example/app/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, CreateView
from .models import Product
from .forms import ProductForm

# Create your views here.
def index(request):
    return render(request, template_name='app/index.html')

class StartView(TemplateView):
    template_name = 'base.html'

class ProductListView(ListView):
    model = Product
    template_name = 'app/products.html'
    context_object_name = 'products'

class ProductCreateView(CreateView):
    form_class = ProductForm
    template_name = 'app/create.html'
    success_url = reverse_lazy('app:products')

webinar/example/app/templates/app/create.html
{% extends 'base.html' %}

{% block content %}
<h1>
    Create product
</h1>

<form method="POST">
    {% csrf_token %}
    {{ form.as_div }}

    <button> type="submit">Отправить</button>

</form>


{% endblock content %}

webinar/example/app/templates/app/index.html
{% extends 'base.html' %}

{% block content %}
<a href="{% url 'app:start' %}">Base</a>
<p>
    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam asperiores dignissimos,
    dolor dolorum error eum fuga harum minus molestias quaerat quasi recusandae rem sunt, tenetur ut.
    Asperiores consequuntur earum esse fugiat, hic itaque laboriosam odit quaerat qui quia,
    quis quod recusandae sapiente tempora voluptate! Amet asperiores assumenda cumque ducimus praesentium.
</p>

{% endblock content %}

webinar/example/app/templates/app/products.html
{% extends 'base.html' %}

{% block content %}
<h1>
    All products
</h1>

{% if products %}
{% for product in products %}
<div>

{{product.name}}
{{product.price}}
{{product.type}}
{{product.description}}
</div>
{% endfor %}

{% else %}
<h3>
    Сорян, но продуктов нет
</h3>
{% endif %}

{% endblock content %}

webinar/example/templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
          crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
            crossorigin="anonymous"></script>
    <title>Title</title>
</head>
<body>
    <H1> Hello from base bootstrap </H1>

    {% block content %}
    {% endblock content %}
</body>
</html>